name: Generate Doxygen Docs

on:
  push:
    tags:
      - 'v*'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Doxygen
      run: sudo apt-get install doxygen graphviz -y

    - name: Run Doxygen
      run: doxygen Doxyfile

    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: doxygen-docs
        path: html/
